atlassian-labs/atlassian-slack-integration-server

pom.xml
These dependencies were included into parent pom.xml, but weren't actually used in any of the sub-modules. It is safe to delete them to please Dependabot.
=> Removed unused dependencies that Dependabot has concerns about

.github/workflows/all-tests.yml, README.md, bin/pack-common.sh, bin/pack-compat-jira.sh, bin/pack-plugin.sh, bin/release-check/fetch-release-issue.sh, bin/run-bitbucket-its.sh, bin/run-bitbucket.sh, bin/run-confluence.sh, bin/run-jira.sh, bin/test-with-coverage.sh, bitbucket.sh, confluence-slack-server-integration-plugin/src/test/java/it/com/atlassian/confluence/plugins/slack/web/ConfigurationWebTest.java, confluence.sh, jira.sh
1. Release checker now can look for closed issues with specified label. Apparently, documentation misses that only open issues are searched by default: https://docs.github.com/en/rest/reference/issues#list-repository-issues.
2. Replaced `mvn` in the scripts used in dev loop with `atlas-mvn` like it was done previously in build scripts run by CI.
=> Release checker respect closed issues

slack-server-integration-common/src/main/resources/admin/connect/connect-workspace.js
The current link to https://api.slack.com/apps?new_app=1 takes the user to create a new application however the current integration requires [what's considered a "classic" Slack app](https://api.slack.com/authentication/quickstart) which can be created by going to https://api.slack.com/apps?new_classic_app=1 instead.
---
=> Update 'connect [Slack] workspace' link to create a new classic app

.github/workflows/all-tests.yml, README.md
With this change Jira 8.12.2 will be used in integration tests by default.
=> #45: Bumped latest supported Jira version to 8.12.2

.github/workflows/all-tests.yml, README.md
Adding Bitbucket 7.6.0 as the latest supported version to test suite and README.
=> #49: Bumped latest supported Bitbucket version to 7.6.0

.github/workflows/all-tests.yml, README.md
Adding Confluence 7.8.0 as the latest supported version to test suite and README.
=> #49: Bumped latest supported Confluence version to 7.8.0

jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/impl/JiraPostFunctionEventRenderer.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/notification/impl/JiraPostFunctionEventRendererTest.java
It's a fix for the issue allowing to execute arbitrary code from withing the custom notification template renderer.
=> Prevented dynamic class loading possibility

jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/manager/impl/DefaultDedicatedChannelManager.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/model/EventMatcherType.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/model/event/DefaultJiraIssueEvent.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/model/event/JiraIssueEvent.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/IssueFilter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/IssueFilterService.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/AbstractSimpleIssueFilter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/DefaultIssueFilterService.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/IssuePriorityFilter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/IssueTypeFilter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/JqlIssueFilter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/listener/IssueEventToEventMatcherTypeConverter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/listener/impl/DefaultIssueEventToEventMatcherTypeConverter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/listener/impl/DefaultJiraSlackEventListener.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/PersonalNotificationManager.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/impl/DefaultIssueEventProcessorService.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/impl/JiraIssueEventRenderer.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/util/changelog/ChangeLogExtractor.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/util/changelog/ChangeLogItem.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/manager/impl/DefaultDedicatedChannelManagerTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/DefaultIssueFilterServiceTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/IssuePriorityFilterTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/IssueTypeFilterTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/JqlIssueFilterTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/listener/impl/DefaultJiraSlackEventListenerTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/notification/impl/DefaultIssueEventProcessorServiceTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/notification/impl/JiraIssueEventRendererTest.java
In this PR I have made issue transition notifications sent on `IssueChangedEvent`'s, rather than on `IssueEvent`'s. `IssueEvent` is still responsible for sending other notifications. After this migration all transition events should be detected correctly and related Slack notifications should be sent even for custom issue statuses and custom events.
=> #24: Fix missing transition notifications

bitbucket-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/manager/impl/DefaultProjectConfigurationManager.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/model/EventMatcherType.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/model/event/DefaultJiraIssueEvent.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/model/event/JiraIssueEvent.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/JqlIssueFilter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/listener/impl/DefaultIssueEventToEventMatcherTypeConverter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/listener/impl/DefaultJiraSlackEventListener.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/impl/DefaultIssueEventProcessorService.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/impl/JiraIssueEventRenderer.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/util/matcher/WorkflowStatusMatcher.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/listener/impl/DefaultIssueEventToEventMatcherTypeConverterTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/listener/impl/DefaultJiraSlackEventListenerTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/notification/impl/DefaultIssueEventProcessorServiceTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/notification/impl/JiraIssueEventRendererTest.java, pom.xml
1. After bumping JUnit in #98 JUnit tests that were run by Jupiter engines stopped running. They were silently ignored and didn't even fail the build. I accidentally discovered it just today. I upgraded Jupiter to the latest version and it worked! 
2. Tests started running again and it appeared that a lot of them are failing. Not because of the issue in the plugin code, just due to outdated tests. I fixed them all as well.
3. There is another issue in Jira plugin that was reported by customers: some project configurations don't have an owner assigned (probably because of downgrade after running a DB migration) and they stopped sending notifications. It is also fixed.
=> Made Jupiter running JUnit tests again and fixed all failed tests

bin/build/run-jira-its.sh, confluence-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/pom.xml, pom.xml, slack-server-integration-common/pom.xml
Release checker have created tickets for compatibility with Jira 8.17.0 and Jira 8.17.1 recently and all integrations tests failed for that versions. As far I understood it happened because Jira team upgraded some libraries used in integration tests, but Slack plugins continued to use hard-coded versions of the libraries. I removed some hard-coded test dependencies where it was possible, and added an override of system property `atlassian.selenium.version` in integration tests for Jira 8.17.1 and newer. It allowed to run integration tests on oldest and newest supported versions.
Here are the successful integration test runs against Jira 8.17.1 in this branch:
* Java 8: https://github.com/atlassian-labs/atlassian-slack-integration-server/runs/2989172142?check_suite_focus=true
* Java 11: …
=> #117: Made integration tests compatible with Jira 8.17.1

jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/bridge/jql/impl/JqlIndexSearcher.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/bridge/jql/impl/JqlIndexSearcherTest.java
There were reports of scaling problems caused by the plugin reindexing more than necessary.
=> Prevent triggering full reindex

slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/DefaultSlackClientProvider.java
Some large Jira DC instances are seeing timeout errors on retry interceptors (backoff + rate limit).
After some research I noticed we are not setting the `writeTimeout` option in OkHttp, which means if we don't write after 10 seconds the connection will time out.
With this constraint, single retries would perform just fine but rate limits and subsequent retries would probably take longer than 10 seconds and thus timeout, to which logically follows that in very busy instances timeouts would occur more often, specially since we await for Slack's "retry after" header, which could take several seconds.
This PR sets the write timeout to 120 seconds, which should work in most cases.
=> Adding write timeout to HTTP client in order to mitigate timeouts upon interceptor retries

bitbucket-slack-server-integration-plugin/pom.xml, pom.xml
According to https://github.com/square/okhttp/issues/3146#issuecomment-569986444 an issue with stale connections that caused SocketTimeoutException errors was fixed in 3.14.5.
=> Bump okhttp3 to 3.14.9

README.md, jira-slack-server-integration/jira-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/impl/DefaultAttachmentHelper.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/impl/JiraIssueEventRenderer.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/util/CommentUtil.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/util/CommentUtilTest.java
Valid Jira text formatting syntax is rendered correctly in Jira, but is shown in raw form in Slack notifications. If text was coloured, Slack added color tags to comment. To fix this bug, i used regex to get the message without tags.
=> Fixed leaking color syntax from Jira to Slack

jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/listener/SlackEventHandlerService.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/notification/impl/ConfigurationEventRenderer.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/listener/SlackEventHandlerServiceTest.java
Bot sent the connection prompt message to the user when the link unfurling was disabled. To disable it, i added a check of checkbox value for previews in project settings and globally.
=> Disabled connection prompt message when link unfurling is disabled

slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/AppHomeOpenedSlackEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/AppUninstalledSlackEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/ChannelArchiveSlackEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/ChannelDeletedSlackEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/ChannelUnarchiveSlackEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/GenericMessageSlackEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/LinkSharedSlackEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/MemberJoinedChannelSlackEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/SlackSlashCommand.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/TokensRevokedSlackEvent.java
I updated samples of Slack webhooks payloads using mitmproxy and got rid of "authed_users" mentions in the source code
=> Got rid of "authed_users" mentions in the source code

bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/listener/SlackChannelEventListener.java, bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/notification/configuration/DefaultNotificationConfigurationService.java, bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/notification/configuration/dao/AoNotificationConfigurationDao.java, bitbucket-slack-server-integration-plugin/src/test/java/com/atlassian/bitbucket/plugins/slack/listener/SlackChannelEventListenerTest.java, bitbucket-slack-server-integration-plugin/src/test/java/com/atlassian/bitbucket/plugins/slack/notification/configuration/dao/AoNotificationConfigurationDaoTest.java, confluence-slack-server-integration-plugin/src/main/java/com/atlassian/confluence/plugins/slack/spacetochannel/configuration/SpaceToChannelConfiguration.java, confluence-slack-server-integration-plugin/src/main/java/com/atlassian/confluence/plugins/slack/spacetochannel/listener/SlackChannelEventListener.java, confluence-slack-server-integration-plugin/src/main/java/com/atlassian/confluence/plugins/slack/spacetochannel/service/DefaultSlackSpaceToChannelService.java, confluence-slack-server-integration-plugin/src/test/java/com/atlassian/confluence/plugins/slack/spacetochannel/listener/SlackChannelEventListenerTest.java, confluence-slack-server-integration-plugin/src/test/java/com/atlassian/confluence/plugins/slack/spacetochannel/service/DefaultSlackSpaceToChannelServiceTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/manager/impl/DefaultProjectConfigurationManager.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/model/dto/ProjectToChannelConfigurationDTO.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/postfunction/SlackPostFunctionFactory.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/resources/slack-soy/channelmapping/channelmapping.soy, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/manager/impl/DefaultProjectConfigurationManagerTest.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/ConversationKey.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/ConversationLoaderHelper.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/ConversationsAndLinks.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/DefaultSlackClient.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/descriptor/DefaultNotificationTypeService.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/events/SlackConversationsLoadedEvent.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/settings/DefaultSlackSettingsService.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/settings/SlackSettingService.java, slack-server-integration-common/src/test/java/com/atlassian/plugins/slack/api/descriptor/DefaultNotificationTypeServiceTest.java, slack-server-integration-common/src/test/java/com/atlassian/plugins/slack/settings/DefaultSlackSettingsServiceTest.java
I replaced channelId to composite Key - class ConversationKey that contains teamId and channelId
=> Added handling for channels in different workspaces that share the same ID

confluence-slack-server-integration-plugin/src/main/java/com/atlassian/confluence/plugins/slack/spacetochannel/listener/ConfluenceEventListener.java
I replaced line where Slack notification referred to the author of page with the line where it is correctly referred to the comment creator
=> #122: Slack notification correctly refers to the comment creator when a user adds a comment in a page

bitbucket-slack-server-integration-plugin/pom.xml, pom.xml
After removal of the parent project from POMs organization information was lost. I added it back explicitly.
=> Added organization tag to POM files

bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/listener/BitbucketNotificationEventListener.java, bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/model/ExtendedChannelToNotify.java, bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/model/NotificationRenderingOptions.java, bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/notification/BitbucketPersonalNotificationTypes.java, bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/notification/NotificationPublisher.java, bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/notification/configuration/PersonalNotificationService.java, bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/notification/renderer/SlackNotificationRenderer.java, bitbucket-slack-server-integration-plugin/src/test/java/com/atlassian/bitbucket/plugins/slack/listener/BitbucketNotificationEventListenerTest.java, bitbucket-slack-server-integration-plugin/src/test/java/com/atlassian/bitbucket/plugins/slack/notification/configuration/PersonalNotificationServiceTest.java, bitbucket-slack-server-integration-plugin/src/test/java/com/atlassian/bitbucket/plugins/slack/notification/renderer/SlackNotificationRendererTest.java
There was handling one of a few event listeners. I added handling event when user add reviewer on PR creation
=> #103: Fixed sending personal notification about adding user as a reviewer on PR creation

jira-slack-server-integration/jira-slack-server-integration-plugin/pom.xml, pom.xml
Gson 2.8.5 -> 2.8.9.
Vulnerability: https://snyk.io/vuln/maven:com.google.code.gson%3Agson
=> Gson vulnerabiilty fix

jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/bridge/jql/impl/JqlIndexSearcher.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/JqlIssueFilter.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/bridge/jql/impl/JqlIndexSearcherTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/issuefilter/impl/JqlIssueFilterTest.java
I moved reindexing of an issue from the loop. So, now it is reindexed before matching against the custom JQL just once. If the issue is not present in the index after the reindexing, the plugin retries 3 more time with 2 seconds interval between attempts (just like now). It should improve performance on big Jira instances.
=> Issue #136: Prevent redundant reindexing

jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/java/com/atlassian/jira/plugins/slack/service/task/impl/SendNotificationTask.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/com/atlassian/jira/plugins/slack/service/task/impl/SendNotificationTaskTest.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/RetryLoaderHelper.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/util/ErrorResponse.java
Slack `chat.postMessage` started responding with `rich_text` block that `jslack` doesn't support. It throws an exception that is considered being an authentication issue, that causes a retry with new credentials. The purpose of this PR is to prevent retries on API response parsing errors to prevent duplicate notifications being to Slack channels. It doesn't solve the issue with parsing. It will be fixed next as it requires more time.
=> Issue #228: Added ignoring of rich_text block parsing error

.github/workflows/all-tests.yml, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/DefaultSlackClientProvider.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/RetryLoaderHelper.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/jslack/PatchedGsonLayoutBlockFactory.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/jslack/PatchedSlackHttpClient.java, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/client/jslack/UnsupportedLayoutBlock.java
Hotfix for this issue was implemented in #229 . The problem with that implementation is that `jslack` throws an exception on every notification being sent to Slack. The plugin correctly handles that exception, but it is still suboptimal solution. In this PR `jslack` is patched to not throw an exception at all.
Also, a small fix was added to the build script to fix CI failures when a commit message contains a quote a double quote.
=> Issue/228: Patch jslack to stop it throwing an exception on unknown blocks

.github/workflows/all-tests.yml, .github/workflows/jira-int-tests.yml, .github/workflows/release.yml, README.md, bitbucket-slack-server-integration-plugin/pom.xml, confluence-slack-integration/confluence-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/jira-8-compat/pom.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/resources/log4j2.xml, jira.sh, pom.xml
- I added Jira 9.5.0 to the supported Jira versions and set Jira 8.15.0 as the oldest supported version since it reached its [End of Life date](https://confluence.atlassian.com/support/atlassian-support-end-of-life-policy-201851003.html).
- Java 17 is now supported by Jira 9.5.0. To implement it:
- AMPS version was bumped.
- Lombok version was bumped to the latest one.
- Maven 3.8.6 is now used in Jira integration tests workflow.
- `opens` and `exports` instructions were added to the JVM command arguments. It is needed because of enforcement of Java module policies in Java 17
-  `-XX:MaxPermSize` command line options was removed because it is remove in Java 17 and now blocks JVM start up.
- Log4j config was replicated in Log4j2 XML format
=> Issue 230: Jira 9.5 support

.github/workflows/all-tests.yml, .github/workflows/bitbucket-int-tests.yml, README.md, bin/build/install-supported-git.sh, bitbucket-slack-server-integration-plugin/pom.xml
Bitbucket integration tests started failing some time ago. It was caused by the change in image used by Github Actions for tests - recently release git 2.38.1 was installed. The problem was that Bitbucket doesn't yet support this git version and just fails to start.
So, I had to downgrade git to latest supported version 2.37.4 before running Bitbucket integration tests. These is no easy way to do that because Ubuntu repository doesn't store all package versions and doesn't even contain the latest version. The only version currently present there is 2.25.1, that is [too old for BItbucket to support](https://confluence.atlassian.com/bitbucketserver/supported-platforms-776640981.html#Supportedplatforms-dvcsDVCS) =( So, the only option left was to build git of the needed version from scratch. …
=> Issue 242: Added installation of the supported git version before running Bitbucket integration tests

.github/workflows/all-tests.yml, bitbucket-slack-server-integration-plugin/pom.xml, confluence-slack-integration/confluence-slack-server-integration-plugin/pom.xml, pom.xml
- Confluence 8 doesn't support Java 8 anymore, but supports Java 17. These changes were added to test workflow files.
- Also, to run Confluence 8 on Java 11 additional Java options need to be passed on startup. 
- `-XX:MaxPermSize` support was dropped on Java 17, so it needed to be removed from params list.
=> Issue 245: Fixed integration tests for Confluence 8

.github/workflows/all-tests.yml, README.md, bitbucket-slack-server-integration-plugin/pom.xml
* Integration tests were failing because of disallowed combination of JDBC parameters. It was legal on H2 used in Bitbucket 8.7, but became disallowed in H2 used in Bitbucket 8.8.
* Also JDK 17 is now supported. In order to run Bitbucket on it, additional opens/exports need to be added to command line arguments like it was already done for Jira and Confluence plugins.
* Since we need to support Bitbucket 8.8 I also added it to the `all-tests.yml`.
=> Issue #259: Bitbucket 8.8 support

bin/release-check/check-release.sh
Added Java 17 to the release check pipeline since all Bitbucket, Confluence, Jira now support Java 17 and we're having to run manual triggers for Java 17 checks.
=> resolves #263 Added JDK 17 in release check pipeline

jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/resources/atlassian-plugin.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/resources/js/lib/backbone-amd.js
Dedicated channel deletion  client-side logic relies on Backbone 1.0.0 API and upgrade to 1.3.3 broke it. Rolling it back to make dedicated channel deletion working again.
=> Issue #274: Rolled back Backbone to 1.0.0

jira-slack-server-integration/jira-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/pom.xml
DbConsole got broken some time ago. Upgrading AMPS seems to fix it.
This change affects only local development.
=> Made DbConsole working again

README.md, bitbucket-slack-server-integration-plugin/pom.xml, bitbucket-slack-server-integration-plugin/src/main/resources/com/atlassian/bitbucket/plugins/slack/bitbucket-slack.properties, bitbucket-slack-server-integration-plugin/src/test/java/it/com/atlassian/bitbucket/plugins/slack/functional/WorkspaceLinkFuncTest.java, bitbucket-slack-server-integration-plugin/src/test/java/it/com/atlassian/bitbucket/plugins/slack/web/ConfigurationWebTest.java, confluence-slack-integration/confluence-7-compat/pom.xml, confluence-slack-integration/confluence-8-compat/pom.xml, confluence-slack-integration/confluence-compat-common/pom.xml, confluence-slack-integration/confluence-slack-server-integration-plugin/pom.xml, confluence-slack-integration/confluence-slack-server-integration-plugin/src/main/resources/com/atlassian/confluence/plugins/slack/confluence-slack.properties, jira-slack-server-integration/jira-8-compat/README.md, jira-slack-server-integration/jira-8-compat/pom.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/src/main/resources/com/atlassian/jira/plugins/slack/jira-slack.properties, slack-server-integration-common/pom.xml, slack-server-integration-common/src/main/java/com/atlassian/plugins/slack/api/webhooks/action/BlockSlackAction.java
As the company changes its focus on supporting Data Center edition of products, the plugins get renamed as well. They are already renamed on Marketplace, this PR changes product mentions in various plugins messages.
=> Change "Server" with "Data Center" in text labels in the plugins

jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/it/com/atlassian/jira/plugins/slack/functional/SanityCheckFuncTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/it/com/atlassian/jira/plugins/slack/functional/UnfurlingFuncTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/it/com/atlassian/jira/plugins/slack/functional/UserLinkFuncTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/it/com/atlassian/jira/plugins/slack/functional/WorkspaceLinkFuncTest.java, jira-slack-server-integration/jira-slack-server-integration-plugin/src/test/java/it/com/atlassian/jira/plugins/slack/web/ConfigurationWebTest.java
Jira builds fail because of invalid license. Server license is provided in integration tests, but Jira stopped accepting it and now wants DC license only. So that replacing the old one
=> Replace Jira testing license by compatible with Data Center

bitbucket-slack-server-integration-plugin/src/main/java/com/atlassian/bitbucket/plugins/slack/listener/BitbucketNotificationEventListener.java, bitbucket-slack-server-integration-plugin/src/test/java/com/atlassian/bitbucket/plugins/slack/listener/BitbucketNotificationEventListenerTest.java
Should reduce noise introduced in #277 and solve part of #344
=> #344 Ignore RESCOPED event without any changes to target PR

.github/workflows/all-tests.yml, README.md, bin/build/run-confluence-its.sh, bin/build/run-unit-tests.sh, bin/run-bitbucket.sh, bin/run-confluence.sh, confluence-slack-integration/confluence-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/pom.xml
- Bump Confluence AMPS plugin version to 9.0.4
- Bump Jira version to 10.0.0-m0010
- Remove `enforcer.skip=true` flags
=> Align with latest available products versions

bitbucket-slack-server-integration-plugin/pom.xml, confluence-slack-integration/confluence-slack-server-integration-plugin/pom.xml, confluence-slack-integration/confluence-slack-server-integration-plugin/src/test/java/it/com/atlassian/confluence/plugins/slack/util/SlackWebTestBase.java, confluence-slack-integration/confluence-slack-server-integration-plugin/src/test/java/it/com/atlassian/confluence/plugins/slack/web/ConfigurationWebTest.java, jira-slack-server-integration/jira-8-compat/pom.xml, jira-slack-server-integration/jira-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/pom.xml, pom.xml, slack-server-integration-common/pom.xml
Bump AMPS plugins to 9.1.11.
Update platform to 7.2.6.
Add `atlassian.authentication.legacy.mode` property 
Disable verify-fe-manifest-associations.
=> Bump dependencies and fix tests against new products' releases

bitbucket-slack-server-integration-plugin/pom.xml, confluence-slack-integration/confluence-slack-server-integration-plugin/pom.xml, jira-slack-server-integration/pom.xml
Integration tests against latest products:
- Bitbucket 9.6.3 - https://github.com/atlassian-labs/atlassian-slack-integration-server/actions/runs/15946981591
- Confluence 9.5.1 - https://github.com/atlassian-labs/atlassian-slack-integration-server/actions/runs/15946971020
- Jira 10.7.1 - https://github.com/atlassian-labs/atlassian-slack-integration-server/actions/runs/15946951395
=> Separate product's api version and version used for integration tests
